---
title: "R Notebook"
output: html_notebook
---

```{r}
#importing the required libraries
library(tidyverse)
library(lubridate)
library(RColorBrewer)
```

```{r}
#reading in the dataset
df <- read.csv("cleaned_dataset.csv")
```

```{r}
#checking the main dataframe
head(df)
```

```{r}
#keeping only the necessary column for the question
q3 <- df %>% select(Year_month)
```

```{r}
#checking for null values
sum(is.na(q3))
```

```{r}
#checking the data type of the columns
str(q3)
```

```{r}
#grouping the data according to the Year_month and counting the number of flights in each Year_month
grouped <- q3 %>% group_by(Year_month) %>% summarise(Count = n())
```

#getting a colour-blind friendly, colour palette
```{r}
display.brewer.all(colorblindFriendly = TRUE)
```

```{r}
my_palette<-brewer.pal(n = 12, name = "Paired")
```



```{r}
#plotting a time series graph to show the number of flights over time
grouped <- q3 %>%
  group_by(Year_month) %>%
  summarize(Count = n())

grouped %>%
  ggplot(aes(x=Year_month, y = Count, group=1)) +
  geom_line(color = my_palette[2]) +
  ggtitle("Trend of the number of flights over time") +
  labs(x= "Year-Month", y = "Number of flights") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5)) +
  theme(plot.title = element_text(hjust = 0.5))

ggsave("Trend in R.png")
```

